openapi: "3.0.1"
info:
  title: "Product API"
  version: "2025-02-22 19:17:19UTC"
servers:
- url: "https://am2xsc1rw3.execute-api.eu-north-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "development"
tags:
- name: "aws:cloudformation:stack-id"
- name: "aws:cloudformation:stack-name"
- name: "aws:cloudformation:logical-id"
paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    count:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
  /products/{product_id}:
    get:
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  count:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
        "404":
          description: Product not found
    parameters:
    - name: "product_id"
      in: "path"
      description: "Generated path parameter for product_id"
      required: true
      schema:
        type: "string"
